#!/usr/bin/env bash

find_up_dir() {
  (
    while true; do
      if [[ -d $1 ]]; then
        echo "$PWD/$1"
        return 0
      fi
      if [[ $PWD == / ]] || [[ $PWD == // ]]; then
        return 1
      fi
      cd ..
    done
  )
}


add_extra_vim_dir() {
    local extravim="$(find_up_dir .vim/)"
    if [ -n "$extravim" ]; then
        # echo "Adding extra .vim/: ${extravim}"
        path_add DIRENV_VIM_DIR $extravim
    fi
}

add_extra_vimrc() {
    local extravim="$(find_up .vimrc)"
    if [ -n "$extravim" ]; then
        # echo "Adding extra .vim/: ${extravim}"
        path_add DIRENV_VIMRC $extravim
    fi
}

layout_anaconda() {
    init_anaconda() {
        __conda_setup="$('/home/pratik/.miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
        if [ $? -eq 0 ]; then
            eval "$__conda_setup"
        else
            if [ -f "/home/pratik/.miniconda3/etc/profile.d/conda.sh" ]; then
                . "/home/pratik/.miniconda3/etc/profile.d/conda.sh"
            else
                export PATH="/home/pratik/.miniconda3/bin:$PATH"
            fi
        fi
        unset __conda_setup
    }
    init_anaconda

    if [ -n "$1" ]; then
        # Explicit environment name from layout command.
        local env_name="$1"
        conda activate ${env_name}
    elif (grep -q name: environment.yml); then
        # Detect environment name from `environment.yml` file in `.envrc` directory
        ENV=$(grep name: environment.yml | sed -e 's/name: //' | cut -d "'" -f 2 | cut -d '"' -f 2)
        conda activate $ENV
        if [ $? -eq 0 ]; then
            :
        else
            # Create the environment and activate
            echo "Conda env '$ENV' doesn't exist."
            conda env create --quiet --file environment.yml
            conda activate $ENV
        fi
    else
        (>&2 echo No environment specified);
        exit 1;
    fi;
}

init_py_venv_layout() {
    if [ -f "Pipfile" ]; then
        layout_pipenv
    elif [ -f "environment.yml" ]; then
        layout_anaconda
    fi
}

# alias_dir=$PWD/.direnv/aliases
# rm -rf "$alias_dir"

# export_alias() {
#   local name=$1
#   shift
#   local target="$alias_dir/$name"
#   mkdir -p "$alias_dir"
#   PATH_add "$alias_dir"
#   echo "#!/usr/bin/env bash" > "$target"
#   echo "$@ \"\$@\"" >> "$target"
#   chmod +x "$target"
# }
