#!/usr/bin/env sh

# stty start undef
# stty stop undef

# stty start undef
# stty stop undef

# shellcheck source=../../nnn/config
[ -s ~/.config/nnn/config ] && . ~/.config/nnn/config

$TERMINAL -e nnn -d "$@"
